#!/usr/bin/env python3
"""
ThreatSwarm Report Generator

Automated pentest report generation from evidence directory structure.

Reads findings from the evidence/ directory, parses structured data,
and generates markdown reports from templates.

Usage:
    python3 report_generate.py generate --type executive --evidence-dir ./evidence --output ./reports/
    python3 report_generate.py generate --type technical --evidence-dir ./evidence --output ./reports/
    python3 report_generate.py generate --type full --evidence-dir ./evidence --output ./reports/
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

__version__ = "1.0.0"

# Severity ordering (higher = more critical)
SEVERITY_ORDER = {"CRITICAL": 5, "HIGH": 4, "MEDIUM": 3, "LOW": 2, "INFO": 1}

# Default template directory (relative to this script)
DEFAULT_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"


def find_finding_files(evidence_dir: Path) -> list:
    """
    Walk evidence directory for finding files.

    Looks for:
    - JSON files matching finding schema (finding.json, findings.json, *.finding.json)
    - Markdown files with CVSS/severity patterns (findings.md, *_findings.md)
    - FINDINGS_SUMMARY.md (auto-generated by findings_sync hook)
    """
    findings = []
    seen = set()

    # JSON finding files
    for pattern in ["**/*finding*.json", "**/finding*.json"]:
        for fpath in evidence_dir.rglob(pattern):
            if fpath not in seen:
                seen.add(fpath)
                try:
                    with open(fpath, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    if isinstance(data, list):
                        for item in data:
                            findings.append(("json", fpath, item))
                    elif isinstance(data, dict):
                        findings.append(("json", fpath, data))
                except (json.JSONDecodeError, OSError):
                    pass

    # Markdown finding files
    for pattern in ["**/*findings*.md", "**/FINDINGS_SUMMARY.md", "**/exploitation.md"]:
        for fpath in evidence_dir.rglob(pattern):
            if fpath not in seen:
                seen.add(fpath)
                findings.append(("markdown", fpath, None))

    return findings


def parse_markdown_findings(filepath: Path) -> list:
    """
    Extract structured findings from a markdown file.

    Looks for patterns like:
    - ## [CRITICAL] Title
    - ### TS-0001: Title
    - CVSS: 3.1/... or CVSS Score: 9.8
    - Tactic: T1059, ATT&CK: T1210, T1078.001
    """
    findings = []
    try:
        content = filepath.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return findings

    # Split into sections by ## headers
    sections = re.split(r"^##\s+", content, flags=re.MULTILINE)

    current_finding = None

    for section in sections:
        # Detect finding headers
        # Pattern: ## [SEVERITY] Title or ## TS-NNNN Title
        header_match = re.match(
            r"\[?(CRITICAL|HIGH|MEDIUM|LOW|INFO)\]?\s*(?:TS-\d+[:\s-]*)?(.+)",
            section[:120], re.IGNORECASE
        )

        if header_match:
            if current_finding:
                findings.append(current_finding)

            severity = header_match.group(1).upper()
            title = header_match.group(2).strip()[:120]

            # Extract CVSS score
            cvss_match = re.search(
                r"CVSS[:\s]+3\.1/(\S+)|CVSS\s+Score[:\s]+([\d.]+)",
                section, re.IGNORECASE
            )
            cvss_score = None
            cvss_vector = None
            if cvss_match:
                if cvss_match.group(2):
                    cvss_score = float(cvss_match.group(2))
                elif cvss_match.group(1):
                    cvss_vector = cvss_match.group(1)
                    # Extract numeric score from vector if possible
                    numeric = re.search(r"(\d+\.\d+)$", cvss_vector)
                    if numeric:
                        cvss_score = float(numeric.group(1))

            # Extract ATT&CK technique IDs
            attack_ids = re.findall(r"\bT\d{4}(?:\.\d{3})?\b", section)

            # Extract finding ID
            id_match = re.search(r"\b(TS-\d+)\b", section[:200])
            finding_id = id_match.group(1) if id_match else None

            # Extract CVE
            cve_match = re.search(r"\b(CVE-\d{4}-\d+)\b", section[:500])
            cve = cve_match.group(1) if cve_match else None

            current_finding = {
                "id": finding_id,
                "title": title,
                "severity": severity,
                "cvss_score": cvss_score,
                "cvss_vector": cvss_vector,
                "attack_techniques": list(set(attack_ids)),
                "cve": cve,
                "source_file": str(filepath),
                "content": section.strip(),
            }
        elif current_finding:
            # Append to current finding content
            current_finding["content"] += "\n\n" + section.strip()

    if current_finding:
        findings.append(current_finding)

    return findings


def parse_json_finding(data: dict) -> dict:
    """Normalize a JSON finding into the standard finding format."""
    return {
        "id": data.get("id"),
        "title": data.get("title", "Untitled"),
        "severity": data.get("severity", "INFO").upper(),
        "cvss_score": data.get("cvss_score"),
        "cvss_vector": data.get("cvss_vector"),
        "attack_techniques": [data["attack_technique"]] if data.get("attack_technique") else [],
        "cve": data.get("cve"),
        "target": data.get("target"),
        "description": data.get("description"),
        "remediation": data.get("remediation"),
        "steps_to_reproduce": data.get("steps_to_reproduce"),
        "business_impact": data.get("business_impact"),
        "references": data.get("references", []),
        "evidence_path": data.get("evidence_path"),
        "source_format": "json",
    }


def collect_all_findings(evidence_dir: Path) -> list:
    """Collect and normalize all findings from evidence directory."""
    raw_findings = find_finding_files(evidence_dir)
    all_findings = []

    for source_type, filepath, data in raw_findings:
        if source_type == "json":
            finding = parse_json_finding(data)
            finding["source_file"] = str(filepath)
            all_findings.append(finding)
        elif source_type == "markdown":
            md_findings = parse_markdown_findings(filepath)
            all_findings.extend(md_findings)

    # Sort by severity (descending) then by CVSS score (descending)
    all_findings.sort(
        key=lambda f: (
            SEVERITY_ORDER.get(f.get("severity", "INFO"), 0),
            f.get("cvss_score") or 0,
        ),
        reverse=True,
    )

    return all_findings


def generate_executive_report(findings: list, evidence_dir: Path, output_dir: Path) -> Path:
    """Generate executive summary report."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"executive_summary_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    # Count by severity
    counts = {}
    for f in findings:
        sev = f.get("severity", "INFO")
        counts[sev] = counts.get(sev, 0) + 1

    total = len(findings)
    lines = []

    lines.append("# Executive Summary — Penetration Test Report\n")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n")
    lines.append(f"**Evidence Directory:** {evidence_dir}\n")
    lines.append(f"**Findings Source:** {total} finding(s)\n")
    lines.append("")
    lines.append("---\n")
    lines.append("")
    lines.append("## Findings Overview\n")
    lines.append("")

    # Severity table
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        if sev in counts:
            lines.append(f"| {sev} | {counts[sev]} |")
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")

    # Visual bar chart
    if total > 0:
        lines.append("### Risk Distribution\n")
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            count = counts.get(sev, 0)
            if count > 0:
                bar = "█" * count
                lines.append(f"{sev:10} {bar} {count}")
        lines.append("")

    # Key findings table
    lines.append("## Key Findings Summary\n")
    lines.append("")
    lines.append("| ID | Finding | Severity | CVSS | ATT&CK |")
    lines.append("|----|---------|----------|------|--------|")
    for f in findings:
        fid = f.get("id") or "—"
        title = f.get("title", "Untitled")[:80]
        severity = f.get("severity", "INFO")
        cvss = f"{f['cvss_score']}" if f.get("cvss_score") is not None else "—"
        attacks = ", ".join(f.get("attack_techniques", [])[:3]) or "—"
        lines.append(f"| {fid} | {title} | {severity} | {cvss} | {attacks} |")
    lines.append("")

    # Top critical findings detail
    critical_findings = [f for f in findings if f.get("severity") == "CRITICAL"]
    high_findings = [f for f in findings if f.get("severity") == "HIGH"]

    if critical_findings or high_findings:
        lines.append("## Critical & High Risk Findings\n")
        for f in critical_findings + high_findings:
            fid = f.get("id") or "—"
            title = f.get("title", "Untitled")
            lines.append(f"\n### [{f.get('severity')}] {fid}: {title}\n")
            content = f.get("content") or f.get("description") or ""
            # First 500 chars of content as summary
            if content:
                summary = content[:500].strip()
                if len(content) > 500:
                    summary += "..."
                lines.append(summary + "\n")
            lines.append("")

    report = "\n".join(lines)
    output_file.write_text(report, encoding="utf-8")
    return output_file


def generate_technical_report(findings: list, evidence_dir: Path, output_dir: Path) -> Path:
    """Generate technical findings report."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"technical_findings_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    lines = []
    lines.append("# Technical Findings Report\n")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n")
    lines.append(f"**Evidence Directory:** {evidence_dir}\n")
    lines.append(f"**Total Findings:** {len(findings)}\n")
    lines.append("")
    lines.append("---\n")

    for i, f in enumerate(findings, 1):
        fid = f.get("id") or f"TS-{i:04d}"
        title = f.get("title", "Untitled")
        severity = f.get("severity", "INFO")
        cvss_score = f.get("cvss_score")
        cvss_vector = f.get("cvss_vector")
        attacks = f.get("attack_techniques", [])
        cve = f.get("cve")
        target = f.get("target")
        source = f.get("source_file", "N/A")

        lines.append(f"## {i}. {fid} — {title}\n")

        # Metadata table
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| **Severity** | {severity} |")
        if cvss_score is not None:
            lines.append(f"| **CVSS Score** | {cvss_score} |")
        if cvss_vector:
            lines.append(f"| **CVSS Vector** | `{cvss_vector}` |")
        if cve:
            lines.append(f"| **CVE** | {cve} |")
        if attacks:
            lines.append(f"| **ATT&CK** | {', '.join(attacks)} |")
        if target:
            lines.append(f"| **Target** | {target} |")
        lines.append(f"| **Source** | {source} |")
        lines.append("")

        # Content
        content = f.get("content") or ""
        if not content:
            content = f.get("description") or ""
        if content:
            lines.append(content + "\n")

        # Steps to reproduce (from JSON)
        steps = f.get("steps_to_reproduce")
        if steps:
            lines.append("### Steps to Reproduce\n")
            for j, step in enumerate(steps, 1):
                lines.append(f"{j}. {step}\n")
            lines.append("")

        # Remediation
        remediation = f.get("remediation")
        if remediation:
            lines.append("### Remediation\n")
            lines.append(remediation + "\n")
            lines.append("")

        # References
        refs = f.get("references", [])
        if refs:
            lines.append("### References\n")
            for ref in refs:
                lines.append(f"- {ref}\n")
            lines.append("")

        lines.append("---\n")

    report = "\n".join(lines)
    output_file.write_text(report, encoding="utf-8")
    return output_file


def generate_full_report(findings: list, evidence_dir: Path, output_dir: Path) -> Path:
    """Generate full report (executive + technical combined)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"full_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"

    exec_report = generate_executive_report(findings, evidence_dir, output_dir)
    tech_report = generate_technical_report(findings, evidence_dir, output_dir)

    exec_content = exec_report.read_text(encoding="utf-8")
    tech_content = tech_report.read_text(encoding="utf-8")

    full = f"""# Penetration Test Report — Full

**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

---

## Table of Contents

1. Executive Summary
2. Technical Findings

---

{exec_content}

---

{tech_content}

---

*Report generated by ThreatSwarm Report Generator v{__version__}*
"""

    output_file.write_text(full, encoding="utf-8")

    # Clean up intermediate files
    try:
        exec_report.unlink()
        tech_report.unlink()
    except OSError:
        pass

    return output_file


def cmd_generate(args: argparse.Namespace) -> None:
    """Handle the 'generate' subcommand."""
    evidence_dir = Path(args.evidence_dir)
    output_dir = Path(args.output)
    report_type = args.type

    if not evidence_dir.exists():
        print(f"[ERROR] Evidence directory not found: {evidence_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"[REPORT] Scanning evidence directory: {evidence_dir}")
    findings = collect_all_findings(evidence_dir)
    print(f"[REPORT] Found {len(findings)} finding(s)")

    if not findings:
        print("[WARN] No findings found. Generating empty report.")
    else:
        sev_counts = {}
        for f in findings:
            sev = f.get("severity", "INFO")
            sev_counts[sev] = sev_counts.get(sev, 0) + 1
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            if sev in sev_counts:
                print(f"  {sev}: {sev_counts[sev]}")

    if report_type == "executive":
        output = generate_executive_report(findings, evidence_dir, output_dir)
    elif report_type == "technical":
        output = generate_technical_report(findings, evidence_dir, output_dir)
    elif report_type == "full":
        output = generate_full_report(findings, evidence_dir, output_dir)
    else:
        print(f"[ERROR] Unknown report type: {report_type}. Use: executive, technical, full", file=sys.stderr)
        sys.exit(1)

    print(f"[REPORT] Generated: {output}")
    print(f"        Size: {output.stat().st_size:,} bytes")


def main():
    parser = argparse.ArgumentParser(
        prog="report_generate",
        description="ThreatSwarm Report Generator — automated pentest report generation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"report_generate {__version__}")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # generate
    p_gen = subparsers.add_parser("generate", help="Generate a report from evidence directory")
    p_gen.add_argument("--type", required=True, choices=["executive", "technical", "full"],
                       help="Report type to generate")
    p_gen.add_argument("--evidence-dir", default="./evidence",
                       help="Evidence directory path (default: ./evidence)")
    p_gen.add_argument("--output", default="./reports",
                       help="Output directory for generated reports (default: ./reports)")
    p_gen.set_defaults(func=cmd_generate)

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    args.func(args)


if __name__ == "__main__":
    main()
